id: P0AD0B42F
initial_creation_type: input
source_metadata:
  Title: Dhih Journal
  Editor: Samten, Ngawang & Janardan Pandey
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '2002'
  Nityakarmapūjāvidhiḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:58:02.881596'
last_modified_at: '2022-03-08T16:58:02.881605'
